- To generate a synthetic marketing data generation engine that simulates real-world omnichannel marketing campaigns, customer engagement, and revenue outcomes with realistic business constraints.

**Import and Configuration**

In [60]:
import numpy as np
import random

random.seed(1)
np.random.seed(1)

In [105]:
brands=['Nike','Adidas','Puma','Reebok','Under Armour']
categories=['Shoes','Apparel','Accesories']

channels=['Facebook','Instagram','Google','YouTube','Email','Display','TV','Radio']
channel_types={"Google": "Search",
                "Facebook": "Social",
                "Instagram": "Social",
                "YouTube": "Video",
                "Email": "Owned",
                "Display": "Display",
                "TV": "Traditional",
                "Radio": "Traditional"}

audiences=['Students','Young Professionals','Parents','Fitness Enthusiasts','Gamers','Corporate']
audience_probability = [0.15, 0.30,0.20,0.20,0.10,0.05]

cities = ["Delhi","Mumbai","Bangalore","Hyderabad","Chennai","Pune","Kolkata"]
city_state = {"Delhi":"Delhi",
              "Mumbai":"Maharashtra",
              "Pune":"Maharashtra",
              "Bangalore":"Karnataka",
              "Hyderabad":"Telangana",
              "Chennai":"Tamil Nadu",
              "Kolkata":"West Bengal"}

campaign_types=['Brand Awareness','Lead Generation','Product Launch','Remarketing','Seasonal','Flash Sale']

project_start = datetime(2024,1,1)
project_end = datetime(2025,12,31)

print("Configuration Loaded Successfully")

Configuration Loaded Successfully

**Channel Table**

In [106]:
import pandas as pd 

channel_rows = []
for i, channel in enumerate(channels, start=1):
    channel_rows.append({"channel_id": f"CH{i:03}",
                        "channel_name": channel,
                        "channel_type": channel_types[channel]})
channels_df = pd.DataFrame(channel_rows)
channels_df

  channel_id channel_name channel_type
0      CH001     Facebook       Social
1      CH002    Instagram       Social
2      CH003       Google       Search
3      CH004      YouTube        Video
4      CH005        Email        Owned
5      CH006      Display      Display
6      CH007           TV  Traditional
7      CH008        Radio  Traditional

In [107]:
channels_df.to_csv("data/raw/channels.csv",index=False)

- **campaign table**

In [66]:
from datetime import datetime,timedelta

num_campaigns=100
budget_ranges = {"Brand Awareness": (300000, 700000),
                 "Lead Generation": (150000, 400000),
                 "Product Launch": (500000, 900000),
                 "Remarketing": (100000, 250000),
                 "Seasonal": (250000, 600000),
                 "Flash Sale": (80000, 180000)}
duration_choices = [30, 45, 60, 90] #days
campaign_status = ["Completed", "Active"]
status_probability = [0.9, 0.1] #90% completed 10% Active

In [95]:
campaign_rows = []
for i in range(1, num_campaigns + 1):
    campaign_id = f"CA{i:03}"
    campaign_type = random.choice(campaign_types)
    
    brand = random.choice(brands)
    category = random.choice(categories)
    campaign_name = f"{brand} {campaign_type}"

    
    budget_min, budget_max = budget_ranges[campaign_type]
    campaign_budget = random.randint(budget_min, budget_max)
    
    
    channel_id = f"CH{random.randint(1, len(channels)):03}"
    
    random_days = random.randint(0,(project_end - project_start).days)
    campaign_start_date = project_start + timedelta(days=random_days)
    duration = random.choice(duration_choices)
    campaign_end_date = campaign_start_date + timedelta(days=duration)

    if campaign_end_date > project_end:
        campaign_end_date = project_end
        
    status = random.choices(campaign_status,weights=status_probability,k=1)[0]

    campaign_rows.append({"campaign_id": campaign_id,
                          "campaign_name": campaign_name,
                          "campaign_type": campaign_type,
                          "brand": brand,
                          "product_category": category,
                          "channel_id": channel_id,
                          "campaign_start_date": campaign_start_date.strftime("%Y-%m-%d"),
                          "campaign_end_date": campaign_end_date.strftime("%Y-%m-%d"),
                          "campaign_budget": campaign_budget,
                          "campaign_status": status})
campaign_df = pd.DataFrame(campaign_rows)
campaign_df.head()

,campaign_id,campaign_name,campaign_type,brand,product_category,channel_id,campaign_start_date,campaign_end_date,campaign_budget,campaign_status
0,CA001,Reebok Brand Awareness,Brand Awareness,Reebok,Apparel,CH002,2024-02-02,2024-05-02,639039,Active
1,CA002,Reebok Lead Generation,Lead Generation,Reebok,Apparel,CH005,2025-01-16,2025-04-16,225922,Completed
2,CA003,Reebok Seasonal,Seasonal,Reebok,Shoes,CH007,2024-04-26,2024-06-10,596286,Completed
3,CA004,Reebok Lead Generation,Lead Generation,Reebok,Apparel,CH001,2024-06-01,2024-07-01,336290,Completed
4,CA005,Nike Product Launch,Product Launch,Nike,Shoes,CH008,2024-06-23,2024-08-22,701468,Completed

In [96]:
campaign_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   campaign_id          100 non-null    object
 1   campaign_name        100 non-null    object
 2   campaign_type        100 non-null    object
 3   brand                100 non-null    object
 4   product_category     100 non-null    object
 5   channel_id           100 non-null    object
 6   campaign_start_date  100 non-null    object
 7   campaign_end_date    100 non-null    object
 8   campaign_budget      100 non-null    int64
 9   campaign_status      100 non-null    object
dtypes: int64(1), object(9)
memory usage: 7.9+ KB

In [51]:
campaign_df["campaign_id"].duplicated().sum()

np.int64(0)

In [50]:
campaign_df["channel_id"].isin(channels_df["channel_id"]).all()

np.True_

In [97]:
campaign_df.to_csv("data/raw/campaigns.csv",index=False,encoding="utf-8")

**Customers Table**

In [69]:
num_customers = 50000
genders = ["Male","Female"]
gender_probability = [0.55,0.45]

age_groups = ["18-24","25-34","35-44","45-54","55+"]
age_probability = [0.20,0.35,0.25,0.15,0.05]

In [70]:
customer_rows=[]

for i in range(1,num_customers+1):
    customer_id=f'CU{i:08}'
    city=random.choice(cities)
    state=city_state[city]
    gender=random.choices(genders,weights=gender_probability,k=1)[0]
    age_group=random.choices(age_groups,weights=age_probability,k=1)[0]
    audience=random.choices(audiences,weights=audience_probability,k=1)[0]

    customer_rows.append({"customer_id": customer_id,
                          "city": city,
                          "state": state,
                          "audience_segment": audience,
                          "gender": gender,
                          "age_group": age_group})
customers_df = pd.DataFrame(customer_rows)
customers_df.head()

  customer_id       city        state     audience_segment  gender age_group
0  CU00000001    Chennai   Tamil Nadu  Young Professionals  Female     18-24
1  CU00000002      Delhi        Delhi              Parents    Male     18-24
2  CU00000003     Mumbai  Maharashtra  Fitness Enthusiasts  Female     35-44
3  CU00000004       Pune  Maharashtra  Young Professionals    Male     25-34
4  CU00000005  Bangalore    Karnataka             Students  Female     25-34

In [30]:
customers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       50000 non-null  object
 1   city              50000 non-null  object
 2   state             50000 non-null  object
 3   audience_segment  50000 non-null  object
 4   gender            50000 non-null  object
 5   age_group         50000 non-null  object
dtypes: object(6)
memory usage: 2.3+ MB

In [31]:
customers_df.isnull().sum()

customer_id         0
city                0
state               0
audience_segment    0
gender              0
age_group           0
dtype: int64

In [32]:
customers_df.duplicated().sum()

np.int64(0)

In [98]:
customers_df.to_csv('data/raw/customers.csv',index=False,encoding='utf-8')

- **external_facters Table**

In [99]:
def get_weather(month):
    if month in [6, 7, 8, 9]:
        return random.choices(["Rainy", "Cloudy", "Sunny"],weights=[0.60, 0.25, 0.15],k=1)[0]
    elif month in [10, 11, 12, 1, 2]:
        return random.choices(["Sunny", "Cloudy", "Rainy"],weights=[0.60, 0.25, 0.15],k=1)[0]
    else:
        return random.choice(["Sunny", "Cloudy", "Rainy"])

In [100]:
date_range = pd.date_range(start=project_start,end=project_end,freq="D")

external_rows = []
decline_start = datetime(2025, 7, 1)

for i, current_date in enumerate(date_range, start=1):
    factor_id = f"EF{i:03}"
    month = current_date.month
    holiday = random.choices(["Yes", "No"],weights=[0.08, 0.92],k=1)[0]
    
    if month in [10, 11, 12]:
        festival = random.choices(["Yes", "No"],weights=[0.25, 0.75],k=1)[0]
    else:
        festival = random.choices(["Yes", "No"],weights=[0.04, 0.96],k=1)[0]    
        
    weather = get_weather(month)

    if current_date >= decline_start: #Competitor spend increases from the point of sales decline
        competitor_spend = random.randint(450000,800000)
    else:
        competitor_spend = random.randint(150000,500000)

    if festival == "Yes":
        discount = random.choice([20, 25, 30, 35, 40])
    else:
        discount = random.choice([0, 5, 10, 15, 20])

    external_rows.append({"factor_id": factor_id,
                          "date": current_date.strftime("%Y-%m-%d"),
                          "holiday_flag": holiday,
                          "festival_flag": festival,
                          "weather": weather,
                          "competitor_spend": competitor_spend,
                          "discount_percentage": discount})
    
external_df = pd.DataFrame(external_rows)
external_df.head()

,factor_id,date,holiday_flag,festival_flag,weather,competitor_spend,discount_percentage
0,EF001,2024-01-01,No,No,Cloudy,348036,20
1,EF002,2024-01-02,No,No,Sunny,196882,0
2,EF003,2024-01-03,No,No,Sunny,159932,20
3,EF004,2024-01-04,No,No,Cloudy,482106,10
4,EF005,2024-01-05,No,No,Sunny,177994,15

In [74]:
external_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   factor_id            731 non-null    object
 1   date                 731 non-null    object
 2   holiday_flag         731 non-null    object
 3   festival_flag        731 non-null    object
 4   weather              731 non-null    object
 5   competitor_spend     731 non-null    int64
 6   discount_percentage  731 non-null    int64
dtypes: int64(2), object(5)
memory usage: 40.1+ KB

In [75]:
external_df.isnull().sum()

factor_id              0
date                   0
holiday_flag           0
festival_flag          0
weather                0
competitor_spend       0
discount_percentage    0
dtype: int64

In [76]:
external_df.duplicated().sum()

np.int64(0)

In [77]:
external_df["factor_id"].is_unique

True

In [101]:
external_df.to_csv("data/raw/external_factors.csv",index=False,encoding="utf-8")

- **marketing_performace Table**

Defining campaign_type behaviours that resembles real-world business

In [108]:
num_records=500000

campaign_rules = {
     #to provide maximum visibility and reach, with low values
    "Brand Awareness": {"ctr": (0.01,0.025),
                        "cvr": (0.01,0.025),
                        "aov": (2500,4500)},

    #to provide maximum reaches
    "Lead Generation": {"ctr": (0.03,0.05), 
                        "cvr": (0.03,0.06),
                        "aov": (3000,6000)},

    "Product Launch": {"ctr": (0.02,0.04),
                       "cvr": (0.02,0.05),
                       "aov": (3500,7000)},

    #to show ads only to the reaches, thus ctr and cvr will be higher
    "Remarketing": {"ctr": (0.05,0.08),
                    "cvr": (0.06,0.10),
                    "aov": (4000,8000)},
    
    "Seasonal": {"ctr": (0.03,0.06),
                 "cvr": (0.04,0.08),
                 "aov": (2500,5500)},

    #to readvertise and will have higher aov
    "Flash Sale": {"ctr": (0.05,0.09),
                   "cvr": (0.05,0.09),
                   "aov": (1800,4000)}}

In [109]:
campaign_lookup = campaign_df.set_index("campaign_id").to_dict("index")
customer_lookup = customers_df.set_index("customer_id").to_dict("index")
external_lookup = external_df.set_index("date").to_dict("index")

campaign_ids = campaign_df["campaign_id"].tolist()
customer_ids = customers_df["customer_id"].tolist()

decline_start = datetime(2025,7,1)

marketing_rows = []
performance_counter=1
while len(marketing_rows) < num_records:
    
    campaign_id = random.choice(campaign_ids)
    campaign = campaign_lookup[campaign_id]
    
    customer_id = random.choice(customer_ids)
    customer = customer_lookup[customer_id]

    campaign_start = datetime.strptime(campaign["campaign_start_date"],"%Y-%m-%d")
    campaign_end = datetime.strptime(campaign["campaign_end_date"],"%Y-%m-%d")

    interaction_date = campaign_start + timedelta(days=random.randint(0,(campaign_end-campaign_start).days))
    interaction_date_str = interaction_date.strftime("%Y-%m-%d")

    # Simulate reduced customer engagement after July 2025
    if interaction_date >= decline_start:
        if random.random() < 0.10:
            continue
    performance_id = f"MP{performance_counter:08}"
    performance_counter += 1
    
    external = external_lookup[interaction_date_str]
    
    factor_id = external["factor_id"]
    
    competitor_spend = external["competitor_spend"]
    
    if interaction_date >= decline_start:
        competitor_spend = int(competitor_spend * 1.25)
        
    discount = external["discount_percentage"]
    
    weather = external["weather"]
    
    festival = external["festival_flag"]
    
    holiday = external["holiday_flag"]

    rules = campaign_rules[campaign["campaign_type"]]
    min_ctr,max_ctr = rules["ctr"]
    min_cvr,max_cvr = rules["cvr"]
    min_aov,max_aov = rules["aov"]

    campaign_duration = (campaign_end - campaign_start).days + 1
    
    daily_budget = campaign["campaign_budget"] / campaign_duration
    spend = random.randint(int(daily_budget*0.70),int(daily_budget*1.10))

    if festival == "Yes":
        spend *= 1.15
    if competitor_spend > 600000:
        spend *= 0.95
    if interaction_date >= decline_start:
        spend *= 0.90      # 10% lower media budget
    spend=int(spend)
    
    cpm = random.randint(150,400)
    if interaction_date >= decline_start:
        cpm = int(cpm * 1.10)

    impressions = int((spend/cpm)*1000)

    reach = random.randint(int(impressions*0.60),impressions)
    if interaction_date >= decline_start:
        reach = int(reach * 0.90)

    frequency = round(impressions/max(reach,1),2)

    ctr = random.uniform(min_ctr, max_ctr)
    if weather == "Rainy":
        ctr *= 0.95
    elif weather == "Cloudy":
        ctr *= 0.98

    if discount >= 30:
        ctr *= 1.10
    elif discount >= 20:
        ctr *= 1.05

    if interaction_date >= decline_start:
        ctr *= 0.88

    clicks = max(1,int(impressions * ctr))

    cvr = random.uniform(min_cvr,max_cvr)
    if holiday == "Yes":
        cvr *= 1.05
        
    if discount >= 30:
        cvr *= 1.15
    elif discount >= 20:
        cvr *= 1.08

    if competitor_spend > 600000:
        cvr *= 0.95
    if interaction_date >= decline_start:
        cvr *= 0.88

    conversions = max(1,int(clicks * cvr))

    aov = random.randint(min_aov,max_aov)
    if festival == "Yes":
        aov *= 1.08
    if interaction_date >= decline_start:
        aov *= 0.95
    aov=int(aov)

    revenue = int(conversions * aov)

    marketing_rows.append({"performance_id": performance_id,
                           "interaction_date": interaction_date.strftime("%Y-%m-%d"),
                           "campaign_id": campaign_id,
                           "customer_id": customer_id,
                           "factor_id": factor_id,
                           "spend": spend,
                           "impressions": impressions,
                           "reach": reach,
                           "frequency": frequency,
                           "clicks": clicks,
                           "conversions": conversions,
                           "revenue": revenue})

marketing_df = pd.DataFrame(marketing_rows)
marketing_df.head()

,performance_id,interaction_date,campaign_id,customer_id,factor_id,spend,impressions,reach,frequency,clicks,conversions,revenue
0,MP00000001,2025-12-26,CA029,CU00042179,EF726,2808,9206,5166,1.78,242,9,27648
1,MP00000002,2025-04-13,CA100,CU00023874,EF469,7499,47764,44339,1.08,600,6,26628
2,MP00000003,2025-12-17,CA041,CU00022611,EF717,8098,31756,27820,1.14,1003,50,260550
3,MP00000004,2025-02-11,CA097,CU00006368,EF408,1441,5650,3780,1.49,393,37,278980
4,MP00000005,2025-09-23,CA077,CU00018756,EF632,6101,21184,13012,1.63,913,55,189695

In [83]:
marketing_df.duplicated().sum()

np.int64(0)

In [84]:
marketing_df["performance_id"].is_unique

True

In [86]:
marketing_df["campaign_id"].isin(campaign_df["campaign_id"]).all()

np.True_

In [87]:
marketing_df["customer_id"].isin(customers_df["customer_id"]).all()

np.True_

In [88]:
marketing_df["factor_id"].isin(external_df["factor_id"]).all()

np.True_

In [110]:
marketing_df.to_csv("data/raw/marketing_performance.csv",index=False,encoding="utf-8")